site_name: GoochLab
site_description: A 15‑acre agritourism, education, and events destination in Goochland County, VA.
site_url: https://blutterfly.github.io/mk_goochland
repo_url: https://github.com/mk_goochland
theme:
  name: material

  palette:                           # light & dark schemes
    - scheme: default               # light
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate                 # dark
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    #  toc.integrate
    - toc.follow               # 2️⃣ TOC stays in right-hand banner
    - navigation.instant
    - content.code.annotate
    - content.tabs.link
  

nav:
  - Home: 
      - index.md
      - Use Cases: 10-use-cases.md
      - Playbook: 11-playbook.md
  
  - Exhibits:
      - Solar Powered Loop: 20-solar-garden-loop.md
      - Van-Life Innovation Station: 21-van-life.md
      - Skoolie Creation Lab: 22-skoolie.md
      - Camping Hiking Gear: 23-camping-hiking.md
      - Bushcraft Upskill Blueprint: 24-bushcraft.md      
  
  - Goochland:
      - Parcel Map: 70-goochland-gis.md      
 
  - Development:
      - Phased Plan: 03-phasing.md
      - Programs & Revenue: 04-programs.md
      - Grants & Funding: 05-grants.md
  
  - Visit Us: 06-visit.md
  - Contact: 07-contact.md
  - About:
    - Vision & Mission: 01-overview.md
    - Site Map: 02-site-map.md

  - DevNotes: 08-dev-notes.md
  # - Consulting: 
  #     - Overview: 50-consulting.md
  #     - Bootcamp: 51-bootcamp.md  
  #     - Bootcamp 2: 52-bootcamp2.md


extra:
  copyright: "@ 2025 Larry Prestosa"

extra_css:
  - stylesheets/extra.css      # create this file in docs/stylesheets/
  - https://cdn.jsdelivr.net/npm/bootswatch@5.3.2/dist/cerulean/bootstrap.min.css

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
  - abbr
repo_url: https://github.com/blutterfly/goochland
edit_uri: ""
